### ISSUE TITLE
swagger-maven-plugin:3.0-SNAPSHOT gives a null pointer exception when trying to do a mvn clean install

### ISSUE THREAD

**Issue by harish2816** [kongchen/swagger-maven-plugin#104]
[ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.0-SNAPSHOT:generate (default) on project restservices: null: MojoExecutionException: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.0-SNAPSHOT:generate (default) on project restservices: null
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException
        at com.github.kongchen.swagger.maven.ApiDocumentMojo.execute(ApiDocumentMojo.java:87)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.NullPointerException
        at java.util.TreeMap.putAll(TreeMap.java:313)
        at com.github.kongchen.swagger.Utils.sortSwagger(Utils.java:70)
        at com.github.kongchen.swagger.AbstractDocumentSource.toDocuments(AbstractDocumentSource.java:166)
        at com.github.kongchen.swagger.maven.ApiDocumentMojo.execute(ApiDocumentMojo.java:76)
        ... 21 more

**Comment by kongchen** [comment]
What's your maven version? I cannot reproduce your issue in my env which is maven 3.2.3

**Comment by danielFesenmeyerAtBosch** [comment]
I'm getting the same exception. My maven version is 3.1.1.

**Comment by websusk** [comment]
I'm also getting the same issue using plugin version 2.3.4 with Maven 3.3.1.  When using any version above 2.3.4, it says it does not know of "apiVersion" and "supportSpringMvc", did you drop support for these?

**Comment by kongchen** [comment]
SpringMvc is not supported in 3.0-M1 by now, I will consider to add the feature in next release, besides 3.0-M1 is using swagger 2.0 spec, which is different from spec 1.2 (supported by the versions 2.3.4), see http://kongchen.github.io/swagger-maven-plugin/ for more details.

**Comment by typekpb** [comment]
as far as I can comment on the `apiVersion` part, following works for me, while using 3.0-M1 version of the plugin:

        </info>
          <version>1</version>
        </info>

**Comment by ndhar-1** [comment]
I see that the fix to the NullPointer Exception has been added for the 3.0-M2 milestone. When is that expected to release ?

**Comment by kongchen** [comment]
@ndhar-1 , I will add springmvc support in 3.0-M2 and I think it will resolve this issue, are you waiting for this?

**Comment by websusk** [comment]
Sort of,  but at your mercy sir.  If I had the time I'd debug and update myself,  but not the case right now unfortunately.

**Comment by ndhar-1** [comment]
Well yes I am trying to use Swagger 2.0 in my project and this NP exception is not letting me move forward. I am not using springmvc. Can the exception be resolved otherwise ?

**Comment by kongchen** [comment]
@ndhar-1 OK, it seems another issue, would you please open a new issue and provide more details such as your configuration, your codes and the NPE stacktrace?

**Comment by ndhar-1** [comment]
Hey, I am talking about the original issue that was opened here on Jan 28. Its the title of this issue. About the NPE, the stack trace you see about is exactly what I am getting. I am just using the Spring-maven-plugin 3.0-SNAPSHOT and not using springmvc.

Caused by: java.lang.NullPointerException
at java.util.TreeMap.putAll(TreeMap.java:313)
at com.github.kongchen.swagger.Utils.sortSwagger(Utils.java:70)
at com.github.kongchen.swagger.AbstractDocumentSource.toDocuments(AbstractDocumentSource.java:166)
at com.github.kongchen.swagger.maven.ApiDocumentMojo.execute(ApiDocumentMojo.java:76)
... 21 more

**Comment by kongchen** [comment]
OK, it's weird. The NPE indicates that swagger reader did not read any api from your codes. It helps if you can paste some code snippet of your resource class.

**Comment by ndhar-1** [comment]
I guess you are talking about the use of annotations. I have used all annotations and it works all good with Swagger 1.2. Here is a snippet:

@ApiModel(description="Resource class")
public class Resource implements Serializable{
	
	private static final long serialVersionUID = 1L;
	
	@ApiModelProperty(required=true, value="Unique identifier for the resource", position=0)
	private String id;

**Comment by ndhar-1** [comment]
my POM:

<dependency>
		<groupId>com.wordnik</groupId>
		<artifactId>swagger-annotations</artifactId>
		<version>1.5.3-M1</version>
	</dependency>
    <dependency>
		<groupId>com.wordnik</groupId>
		<artifactId>swagger-core</artifactId>
		<version>1.5.0-M1</version>
	</dependency>
	<dependency>

**Comment by websusk** [comment]
Sorry,  wrong issue replied to,  disregard

**Comment by ndhar-1** [comment]
Hi kongchen, so could you understand my environment and situation ? you need more details ?

**Comment by kongchen** [comment]
Sorry @ndhar-1 , I'm really busy these days, I wish I could have time this weekend to take care of this project.

**Comment by ndhar-1** [comment]
I understand you would be busy with other projects. It would be great if you could take time to look into this NPE. For now, I cannot go ahead with this plugin. I dont have a need to use spring framework, so I am refraining from springmvc plugin.

**Comment by kongchen** [comment]
Try 3.0-M2-SNAPSHOT

**Comment by ndhar-1** [comment]
I tried 3.0-M2-SNAPSHOT and got rid of the NPE ... yayy !!!!
But do you have an idea which version works good with java UUID datatype? That is giving me an issue.

[INFO] getParameters for class java.util.UUID
[INFO] trying extension com.wordnik.swagger.jersey.SwaggerJerseyJaxrs@67941d
[INFO] no parameter found, looking at body params

My POM has:

com.wordnik
swagger-annotations
1.5.3-M1

com.wordnik
swagger-core
1.5.0-M1

**Comment by kongchen** [comment]
Two more things:

- You'd better use swagger `1.5.1-M2`, that is their [official release](https://github.com/swagger-api/swagger-core#compatibility) for Swagger Spec 2.0
- This plugin's current release version is **`3.0.0`** and latest development version is **`3.0.1-SNAPSHOT`**, you should try that instead of `3.0-M2-SNAPSHOT`.

**Comment by kongchen** [comment]
For your issue, could you please file another issue if it still exists in 3.0.1-SNAPSHOT?
