### ISSUE TITLE
BUG on release 2.3.3 with SpringMvcReader

### ISSUE THREAD

**Issue by brusand** [kongchen/swagger-maven-plugin#111]
there is a bug in the 2.3.3 release with the SpringMvcReader when you add the HttpServletRequest in the last argument) : (i saw that in the sort collection, an argument could be not null but with length=0 wich is not tested and generate this exception (in hash
value method : com.github.kongchen.swagger.docgen.mustache.MustacheDocument$1.hashValue(MustacheDocument.java:171)

	@RequestMapping(value = "/{id}", method = RequestMethod.GET)
	@RoleChecker(authorized = { Role.ALL })
	public Actor getActorExternalOk(@PathVariable("id") String actorId,  HttpServletRequest request) throws Exception {
		String requesterActorId = (String) request.getAttribute(REQUESTER_ACTOR_ID);
		return actorBusEndpoint.getActor(requesterActorId, actorId);
	}

cause :
[ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:2.3.3:generate (default) on project swagger-config: null: MojoExecutionException: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.kongchen:swagger-maven-plugin:2.3.3:generate (default) on project swagger-config: null
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException
        at com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo.execute(ApiDocumentMojo.java:87)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.NullPointerException
        at com.github.kongchen.swagger.docgen.mustache.MustacheDocument$1.hashValue(MustacheDocument.java:171)
        at com.github.kongchen.swagger.docgen.mustache.MustacheDocument$1.compare(MustacheDocument.java:164)
        at com.github.kongchen.swagger.docgen.mustache.MustacheDocument$1.compare(MustacheDocument.java:160)
        at java.util.TimSort.countRunAndMakeAscending(TimSort.java:351)
        at java.util.TimSort.sort(TimSort.java:216)
        at java.util.Arrays.sort(Arrays.java:1512)
        at java.util.ArrayList.sort(ArrayList.java:1439)
        at java.util.Collections.sort(Collections.java:175)
        at com.github.kongchen.swagger.docgen.mustache.MustacheDocument.analyzeParameters(MustacheDocument.java:160)
        at com.github.kongchen.swagger.docgen.mustache.MustacheOperation.<init>(MustacheOperation.java:67)
        at com.github.kongchen.swagger.docgen.mustache.OutputTemplate.createMustacheDocument(OutputTemplate.java:112)
        at com.github.kongchen.swagger.docgen.mustache.OutputTemplate.feedSource(OutputTemplate.java:194)
        at com.github.kongchen.swagger.docgen.mustache.OutputTemplate.<init>(OutputTemplate.java:36)
        at com.github.kongchen.swagger.docgen.AbstractDocumentSource.prepareMustacheTemplate(AbstractDocumentSource.java:342)
        at com.github.kongchen.swagger.docgen.AbstractDocumentSource.toDocuments(AbstractDocumentSource.java:348)
        at com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo.execute(ApiDocumentMojo.java:76)

@tedleman ping

**Comment by brusand** [comment]
add   in MustacheDocument.java line 180 and its works
          private int hashValue(MustacheParameterSet parameterSet) {
                if (parameterSet == null || parameterSet.getParamType() == null || parameterSet.getParamType().length() == 0) {

**Comment by kongchen** [comment]
Thanks for the finding. I will deploy the 2.3.4-SNAPSHOT with this fix, and you'll see it in the snapshot repository as you mentioned in issue#110

**Comment by brusand** [comment]
thx a lot,
it work better ;-)

i post an other issue on data type field name
, it is the last issue before we adopt your (awersome) plugin (i work in a
big (fruit) telecom operator)
 ;-)

Regards
Bruno

2015-02-10 2:24 GMT+01:00 Yukai Kong <notifications@github.com>:
