### ISSUE TITLE
When supportSpringMvc is set to true, only all my APIs show up under the same resourcePath.

### ISSUE THREAD

**Issue by kvelakur** [kongchen/swagger-maven-plugin#120]
We are using swagger-maven-plugin 2.3.3, and swagger-springmvc 0.9.5. Also supportSpringMvc is set to true in the pom, and swaggerDirectory is set, so the Swagger v1.2 json files will be generated. 

We have a few different Spring MVC controllers that are annotated with @Api(value = "/something", description = "some description"). The value="" for the @Api annotations are all different. 

When the project is compiled to generate sources, we notice that only service.json and one other json file is generated, all the APIs are listed under the same path (it chooses a random path value from the @Api annotations).

**Comment by kongchen** [comment]
Would you please try 2.3.4-SNAPSHOT? I think it is fixed.

**Comment by kvelakur** [comment]
Tried the 2.3.4-SNAPSHOT version, but I now see a NPE: 
<pre><code>[ERROR] DOC NOT GENERATED FOR: 4.0.0
java.lang.NullPointerException
	at com.github.kongchen.swagger.docgen.spring.SpringMvcApiReader.generateResponseMessages(SpringMvcApiReader.java:390)
	at com.github.kongchen.swagger.docgen.spring.SpringMvcApiReader.generateOperation(SpringMvcApiReader.java:254)
	at com.github.kongchen.swagger.docgen.spring.SpringMvcApiReader.read(SpringMvcApiReader.java:137)
	at com.github.kongchen.swagger.docgen.mavenplugin.SpringMavenDocumentSource.getDocFromSpringResource(SpringMavenDocumentSource.java:198)
	at com.github.kongchen.swagger.docgen.mavenplugin.SpringMavenDocumentSource.loadDocuments(SpringMavenDocumentSource.java:160)
	at com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo.execute(ApiDocumentMojo.java:64)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
</code></pre>

**Comment by kongchen** [comment]
Sorry, would you please try it again?

**Comment by DVanderstoken** [comment]
I Have the same error with 2.3.4
````
[INFO] --- swagger-maven-plugin:2.3.4:generate (default) @ fva ---
[INFO] Reflections took 62 ms to scan 1 urls, producing 4 keys and 8 values
[ERROR] DOC NOT GENERATED FOR: category
java.lang.NullPointerException
        at com.github.kongchen.swagger.docgen.spring.SpringMvcApiReader.addToModels(SpringMvcApiReader.java:614)
        at com.github.kongchen.swagger.docgen.spring.SpringMvcApiReader.generateResponseMessages(SpringMvcApiReader.java:383)
        at com.github.kongchen.swagger.docgen.spring.SpringMvcApiReader.generateOperation(SpringMvcApiReader.java:254)
        at com.github.kongchen.swagger.docgen.spring.SpringMvcApiReader.read(SpringMvcApiReader.java:137)
        at com.github.kongchen.swagger.docgen.mavenplugin.SpringMavenDocumentSource.getDocFromSpringResource(SpringMavenDocumentSource.java:198)
        at com.github.kongchen.swagger.docgen.mavenplugin.SpringMavenDocumentSource.loadDocuments(SpringMavenDocumentSource.java:160)
        at com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo.execute(ApiDocumentMojo.java:64)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
````

**Comment by kongchen** [comment]
Would you please try to use version 3.0.0 which supports swagger spec 2.0?
