### ISSUE TITLE
Is there a way to get case class fields documented without using @BeanProperty?

### ISSUE THREAD

**Issue by jsw** [kongchen/swagger-maven-plugin#145]
After upgrading from swagger-maven-plugin 2.3.4 to 3.0.0, it appears that my case classes require @BeanProperty in order for the fields to be recognized. This feels intrusive to the scala source. Is there another way to get these fields recognized?

**Comment by kongchen** [comment]
Hi @jsw , I'm not quite farmilar with scala, but I guess the reason is this:

2.3.4 use `swagger-core`'s reader, which is written in Scala. But in 3.0.0, both of this plugin and `swagger-core`'s reader are all written in Java.

**Comment by jsw** [comment]
Please see https://github.com/swagger-api/swagger-core/issues/1060

**Comment by jsw** [comment]
@kongchen,

Have you had a chance to look into this?

**Comment by kongchen** [comment]
I'd like to help, but I'm not familiar with Scala. I think it would be helpful if you could create a sample repo to demonstrate this issue, and then I can clone your repo and try to resolve.

**Comment by jsw** [comment]
Sure, I will set one up.I think it may just be a simple pom change to enable scala support. Should I work off your master branch?

**Comment by who** [comment]
@jsw Yes, master should be fine.

**Comment by jsw** [comment]
See https://github.com/jsw/swagger-maven-plugin-test

Unfortunately, I get a NullPointerException when I use swagger-maven-plugin 3.0.1-SNAPSHOT, which I built from master.

[ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.0.1-SNAPSHOT:generate (default) on project swagger-maven-test: null: MojoExecutionException: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.0.1-SNAPSHOT:generate (default) on project swagger-maven-test: null
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException
	at com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo.execute(ApiDocumentMojo.java:93)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.NullPointerException
	at java.util.TreeMap.putAll(TreeMap.java:308)
	at com.github.kongchen.swagger.docgen.mavenplugin.MavenDocumentSource.loadDocuments(MavenDocumentSource.java:61)
	at com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo.execute(ApiDocumentMojo.java:71)
	... 21 more

Once that is fixed, I will try adding the following dependency to swagger-maven-plugin pom.xml to see if the case class is documented.

	<dependency>
          <groupId>io.swagger</groupId>
          <artifactId>swagger-scala-module</artifactId>
          <version>1.0.0-SNAPSHOT</version>
        </dependency>

**Comment by kongchen** [comment]
Sorry, please try to retrieve the 3.0.1-SNAPSHOT again, I just found the issue and have it fixed.

**Comment by jsw** [comment]
That was quick. :-) 
Adding the dependency mentioned above appears to do the right thing.
Let me know if you want a pull request.
If you compile my project, you will see the fields for the MyWorld case class in the generated api doc. 
Unfortunately the swagger-scala-module is a new project and still at 1.0.0-SNAPSHOT. 
I will inquire if they plan to produce a release version soon.

**Comment by kongchen** [comment]
Yes, PR is welcomed.
I planed to release 3.0.1 in 1 or 2 days, if they could release their 1.0.0 I would add the dependency.

**Comment by polkovnikov-ph** [comment]
`BeanProperty`-marked fields are serialized with duplicate fields into JSON by `jackson` in Scala. Was there a PR that fixes this?
