### ISSUE TITLE
@ApiOperation(hidden=true) leads to NullPointerException in AbstractReader

### ISSUE THREAD

**Issue by gruenebe** [kongchen/swagger-maven-plugin#180]
First of all I need to say, that I love this plugin :)

But when using `@ApiOperation(hidden=true)` to hide a resource completely, I get an Exception during the compile. (https://github.com/swagger-api/swagger-core/wiki/Annotations)

I have verified this with your example app:
https://github.com/kongchen/swagger-maven-example
To reproduce just use `@ApiOperation(hidden=true)` on any resource and compile.

**Comment by who** [comment]
@gruenebe Could you please try again with 3.1.1-SNAPSHOT ?

**Comment by dippinthoughts** [comment]
I don't get a NullPointer anymore with `3.1.1-SNAPSHOT` but I get an almost empty **swagger.json**

`pom.xml`
```

    <build>
        <plugins>
            <plugin>
                <groupId>com.github.kongchen</groupId>
                <artifactId>swagger-maven-plugin</artifactId>
                <version>3.1.1-SNAPSHOT</version>
                <configuration>
                    <apiSources>
                        <apiSource>
                            <locations>foo.bar.rest.resources.official</locations>
                            <basePath>foobar/1.2</basePath>
                            <info>
                                <title>Foo Bar</title>
                                <version>1.2</version>
                            </info>
                            <swaggerDirectory>${basedir}/src/main/resources/api</swaggerDirectory>
                        </apiSource>
                        <apiSource>
                            <locations>foo.bar.rest.resources.official</locations>
                            <basePath>/plugins/foobar/1.2</basePath>
                            <info>
                                <title>Foo Bar</title>
                                <version>1.2</version>
                            </info>
                            <swaggerDirectory>${basedir}/generated/</swaggerDirectory>
                        </apiSource>
                    </apiSources>
                </configuration>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Result:** `swagger.json`

```
{
  "swagger" : "2.0",
  "info" : {
    "version" : "1.2",
    "title" : "Foo Bar"
  },
  "basePath" : "/foobar/1.2"
}
```

I also tested it with the example project and my project. In both cases the swagger.json does not contain any information anymore :(

**Comment by gruenebe** [comment]
I don't get a NullPointer anymore with `3.1.1-SNAPSHOT` but I get an almost empty **swagger.json**

`pom.xml`
```

    <build>
        <plugins>
            <plugin>
                <groupId>com.github.kongchen</groupId>
                <artifactId>swagger-maven-plugin</artifactId>
                <version>3.1.1-SNAPSHOT</version>
                <configuration>
                    <apiSources>
                        <apiSource>
                            <locations>foo.bar.rest.resources.official</locations>
                            <basePath>foobar/1.2</basePath>
                            <info>
                                <title>Foo Bar</title>
                                <version>1.2</version>
                            </info>
                            <swaggerDirectory>${basedir}/src/main/resources/api</swaggerDirectory>
                        </apiSource>
                        <apiSource>
                            <locations>foo.bar.rest.resources.official</locations>
                            <basePath>/plugins/foobar/1.2</basePath>
                            <info>
                                <title>Foo Bar</title>
                                <version>1.2</version>
                            </info>
                            <swaggerDirectory>${basedir}/generated/</swaggerDirectory>
                        </apiSource>
                    </apiSources>
                </configuration>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Result:** `swagger.json`

```
{
  "swagger" : "2.0",
  "info" : {
    "version" : "1.2",
    "title" : "Foo Bar"
  },
  "basePath" : "/foobar/1.2"
}
```

I also tested it with the example project and my project. In both cases the swagger.json does not contain any information anymore :(

**Comment by gruenebe** [comment]
So here is the Output of the example project when I switch to 3.1.1-SNAPSHOT

````
git clone https://github.com/kongchen/swagger-maven-example.git
cd swagger-maven-example
sed -i -e "s/3.0.1-SNAPSHOT/3.1.1-SNAPSHOT/g" pom.xml
mvn compile
cat generated\swagger-ui\swagger.json
````

result
```
{
  "swagger" : "2.0",
  "info" : {
    "description" : "This is a sample for swagger-maven-plugin",
    "version" : "v1",
    "title" : "Swagger Maven Plugin Sample",
    "termsOfService" : "http://www.github.com/kongchen/swagger-maven-plugin",
    "contact" : {
      "name" : "Kong Chen",
      "url" : "http://kongch.com",
      "email" : "kongchen@gmail.com"
    },
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host" : "petstore.swagger.wordnik.com",
  "basePath" : "/api",
  "schemes" : [ "http", "https" ]
}
```

**Comment by who** [comment]
@gruenebe `swagger-maven-plugin` 3.1.0+ uses the new io.swagger.swagger-core v1.5 dependencies.

In version 1.5 of swagger core, the swagger team changed all namespaces of annotations from `com.wordnik.*` to `io.swagger.*`.  

The reason you are seeing an empty spec is because `swagger-maven-plugin` 3.1.0 is looking for the newer namespaced annotations (`io.swagger.*`), not the old `com.wordnik.*` ones.

**Comment by who** [comment]
@gruenebe 

Here's the new pom.xml dependency you will need:

```
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-core</artifactId>
            <version>1.5.0</version>
        </dependency>
```

Git rid of the com.wordnik one.

**Comment by gruenebe** [comment]
Ok I got the new dependencies and withoud `hidden = true` everything works fine.
But when setting `hidden = true` I get this on my project

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.344s
[INFO] Finished at: Thu Jul 02 20:25:56 CEST 2015
[INFO] Final Memory: 25M/353M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.1-SNAPSHOT:generate (default) on project foo: null: MojoExecutionException: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.1-SNAPSHOT:generate (default) on project foo: null
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: org.apache.maven.plugin.MojoExecutionException
	at com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo.execute(ApiDocumentMojo.java:94)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 25 more
Caused by: java.lang.NullPointerException
	at com.github.kongchen.swagger.docgen.reader.AbstractReader.updateOperationParameters(AbstractReader.java:162)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.read(JaxrsReader.java:109)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.read(JaxrsReader.java:67)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.read(JaxrsReader.java:58)
	at com.github.kongchen.swagger.docgen.mavenplugin.MavenDocumentSource.loadDocuments(MavenDocumentSource.java:46)
	at com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo.execute(ApiDocumentMojo.java:72)
	... 27 more
[ERROR] 
```

**Comment by who** [comment]
@gruenebe Ah, that's a bug indeed!

I have pushed a fix for it here: https://github.com/kongchen/swagger-maven-plugin/commit/ea49dbc8ff8fd9884f79c2ab144585d315168b04

I do not have permissions to push snapshots to the snapshot repository (only @kongchen can do that) so if you want this change you'll have to build from source and install the latest snapshot to your local maven repo.

**Comment by gruenebe** [comment]
ok thanks for fixing it :)

I build it lcoally and deployed it to my local artifactory but since it has no unique version maven downloads always the old version. So I am waiting for your depmoyment to public maven repo to verify this.

**Comment by kongchen** [comment]
Thanks @who & @gruenebe !
I have deployed the SNAPSHOT.

**Comment by deeapverma79** [comment]
I am using the following versions of swagger-maven plugin.

                <groupId>com.github.kongchen</groupId>
                <artifactId>swagger-maven-plugin</artifactId>
                <version>3.1.3</version>

And my dependency contains io.swagger as below 

           <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-core</artifactId>
            <scope>compile</scope>
            <version>1.5.3</version>
            <exclusions>
                <exclusion>
                    <groupId>javax.ws.rs</groupId>
                    <artifactId>jsr311-api</artifactId>
                </exclusion>
            </exclusions>
            </dependency>


I get empty swagger.json with some basic information.

I also downloaded the swagger example project and generated the json with no luck. 
Could you please advise , what am I doing wrong ?

**Comment by deeapverma79** [comment]
I tried 
'mvn clean compile swagger:generate' for the example and that worked for me. 

Link --> https://github.com/kongchen/swagger-maven-plugin/issues/241
