### ISSUE TITLE
Honor Enum's value

### ISSUE THREAD

**Issue by dantran** [kongchen/swagger-maven-plugin#258]
Detail discussion at https://github.com/joelittlejohn/jsonschema2pojo/issues/452#issuecomment-159956152

**Comment by dantran** [comment]
Hi,  how complex would be for this fix?  I may be able to get sometime during this holiday to createa PR, with some guidence for swagger-m-p team

**Comment by dantran** [comment]
devs please comment :-) throw me something

**Comment by who** [comment]
@dantran 

Do you have any examples that reproduce the behavior you'd like to fix?

**Comment by dantran** [comment]
Let me summarize the issue from the orignal discussion at schema2pojo

from a java source

    @JsonProperty("state")
    private Task.State state;

    .....

    @Generated("org.jsonschema2pojo")
    public static enum State {

        QUEUED("Queued"),
        WAITING_FOR_RESOURCE("Waiting_for_resource"),
        RUNNING("Running"),
        PENDING_CANCELLATION("Pending_cancellation"),
        COMPLETED("Completed");
....

swagger-maven-plugin generates this

		"state": {
	        "type": "string",
	        "enum": ["QUEUED", "WAITING_FOR_RESOURCE", "RUNNING", ...]
		}

The correct one is

		"state": {
	        "type": "string",
	        "enum": ["Running", "Waiting_for_resource", "Running", ...]
		}

Hope this is enough?

**Comment by who** [comment]
This may be a limitation of swagger-core, which swagger-maven-plugin wraps. 

Could you investigate this? Fork https://github.com/swagger-api/swagger-samples, add in a pojo generated by schema2pojo, and see what the output is.

**Comment by dantran** [comment]
@Who I can create a sample project where it wil start out with jsonschema, to POJO, then to swagger.json.  Is this what you are looking for?

**Comment by who** [comment]
@dantran that would be great, yes

**Comment by dantran** [comment]
@who here you go!  https://github.com/dantran/jsonscheam2swagger-sample

**Comment by corleonis** [comment]
Hi there I have exactly the same issue as dantran. I have a case where I have enum with `@JsonValue` on an internal method. So I get lowercase values and uppercase enum items. Problem is my swagger schema works just fine, I get the lowercase values as expected though when generated through the plugin the JSON's enum values are wrong.

Is there any chance for this to be fixed?

**Comment by danieleorler** [comment]
Hi,
we had the same problem and we worked around it by creating a custom `swaggerApiReader` :

```java
import com.github.kongchen.swagger.docgen.reader.JaxrsReader;

public class SwaggerCustomReader extends JaxrsReader {
    public SwaggerCustomReader(Swagger swagger, Log log) {
        super(swagger, log);
        Json.mapper().configure(SerializationFeature.WRITE_ENUMS_USING_TO_STRING, true);
    }
}
```

and specified it as `swaggerApiReader` on the `apiSource` config in the pom:

```xml
<apiSource>
...
<swaggerApiReader>com.your.package.SwaggerCustomJaxrsReader</swaggerApiReader>
...
</apiSource>
```

now if the enum implements `toString`, it will be serialized using its `toString` method

**Comment by corleonis** [comment]
I've ended up implementing a `value` method for my Enum and annotating that, not very elegant though it worked fine for me. Here is an example:

```
    @ApiModel
    @JsonFormat(shape = JsonFormat.Shape.OBJECT)
    public enum Type {
        ABOUTME("aboutme"),
        GITHUB("github"),
        GOOGLEPLUS("googleplus"),
        GOOGLE("google"),
        TWITTER("twitter"),
        ANGELLIST("angellist"),
        BEHANCE("behance"),
        STACKOVERFLOW("stackoverflow"),
        LINKEDIN("linkedin");

        private final static Map<String, Type> typesLookup = new HashMap<>();

        private final String value;

        static {
            for (Type type : values()) {
                typesLookup.put(type.getValue(), type);
            }
        }

        Type(final String type) {
            value = type;
        }

        public static Type get(String value) {
            return typesLookup.get(value);
        }

        @JsonValue
        public String getValue() {
            return value;
        }
    }
```
So the `getValue()` produces the correct format for the Enum and I can still use it like this `Type::GOOGLE` in the code.

**Comment by dantran** [comment]
@danieleorler where do you place  the customer reader?  put in a jar and push the jar into swagger-maven-plugin as dependency??

**Comment by dantran** [comment]
solution provided by @danieleorler  works for me

but the one from @corleonis is not, very likely a regression at latest swagger-core (1.5.13) where @JasonValue is not  honor

**Comment by warrenc5** [comment]
swagger core (1.5.19) ModelResolver delegates to Jackson Databind (2.8.11) AnnotationIntrospector which just returns the .name() of the enum at this point here!

"main"
	at com.fasterxml.jackson.databind.AnnotationIntrospector.findEnumValue(AnnotationIntrospector.java:1032)
	at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.findEnumValue(AnnotationIntrospectorPair.java:574)
	at io.swagger.jackson.ModelResolver._addEnumProps(ModelResolver.java:207)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:162)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:118)
	at com.github.kongchen.swagger.docgen.reader.ModelModifier.resolveProperty(ModelModifier.java:76)
	at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:83)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:478)
	at com.github.kongchen.swagger.docgen.reader.ModelModifier.resolve(ModelModifier.java:96)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:191)
	at com.github.kongchen.swagger.docgen.reader.ModelModifier.resolve(ModelModifier.java:90)
	at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:103)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:244)
	at com.github.kongchen.swagger.docgen.reader.ModelModifier.resolve(ModelModifier.java:96)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:191)
	at com.github.kongchen.swagger.docgen.reader.ModelModifier.resolve(ModelModifier.java:90)
	at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:103)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:167)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:118)
	at com.github.kongchen.swagger.docgen.reader.ModelModifier.resolveProperty(ModelModifier.java:76)
	at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:83)
	at io.swagger.converter.ModelConverters.readAsProperty(ModelConverters.java:63)
	at io.swagger.converter.ModelConverters.readAsProperty(ModelConverters.java:57)
	at io.swagger.util.ParameterProcessor.applyAnnotations(ParameterProcessor.java:263)
	at com.github.kongchen.swagger.docgen.reader.AbstractReader.getParameters(AbstractReader.java:375)
	at com.github.kongchen.swagger.docgen.reader.AbstractReader.getParameters(AbstractReader.java:346)
	at com.github.kongchen.swagger.docgen.reader.SpringMvcApiReader.parseMethod(SpringMvcApiReader.java:320)
	at com.github.kongchen.swagger.docgen.reader.SpringMvcApiReader.read(SpringMvcApiReader.java:131)
	at com.github.kongchen.swagger.docgen.reader.SpringMvcApiReader.read(SpringMvcApiReader.java:74)
	at com.github.kongchen.swagger.docgen.AbstractDocumentSource.loadDocuments(AbstractDocumentSource.java:104)
	at com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo.execute(ApiDocumentMojo.java:96)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Laun        for (Enum<?> en : enumClass.getEnumConstants()) {
cher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

**Comment by Nic1338** [comment]
A little note for the workaround that @danieleorler provided: 
If you use SpringMvc annotations instead of Jaxrs, then you need to extend SpringMvcApiReader instead of  JaxrsReader.
