### ISSUE TITLE
NullPointerException when @ApiOperation does not define response

### ISSUE THREAD

**Issue by wsalembi** [kongchen/swagger-maven-plugin#267]
After upgrading to 3.1.2, this documentation was broken

```
    @ApiOperation("Returns the swagger.json file describing the service")
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = String.class),
        @ApiResponse(code = 404, message = "Not Found", response = String.class)
    })
```
The correct swagger way should be to document the default success outcome in @ApiOperation

```
    @ApiOperation(value = "Returns the swagger.json file describing the service", response = String.class)
    @ApiResponses({
        @ApiResponse(code = 404, message = "Not Found", response = String.class)
    })
```

Still the error information of the plugin could be more explicit

```
[ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.2:generate (default) on project rest-reference-service: null: MojoExecutionException: NullPointerException -> [Help 1]
```

Full stacktrace
```
java.lang.NullPointerException
	at com.github.kongchen.swagger.docgen.reader.AbstractReader.updateApiResponse(AbstractReader.java:470)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.parseMethod(JaxrsReader.java:318)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.read(JaxrsReader.java:93)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.read(JaxrsReader.java:50)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.read(JaxrsReader.java:41)
	at com.github.kongchen.swagger.docgen.mavenplugin.MavenDocumentSource.loadDocuments(MavenDocumentSource.java:46)
	at com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo.execute(ApiDocumentMojo.java:84)
```

**Comment by who** [comment]
I'm not able to reproduce this.

In my observations, the class below yields the spec below:

**Class**
```java
package com.github.who.smp.tests;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;

/**
 *
 * @author andrewb
 */
@Path("/test")
@Api(tags = {"testing"}, value = "/test")
@Produces({"application/json"})
public class TestingIssue267 {
    @GET
    @Path("/testing1")
    @ApiOperation("testing1")
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = String.class),
        @ApiResponse(code = 404, message = "Not Found", response = String.class)
    })
    public String testing1() {
        return "testing1";
    }

    @GET
    @Path("/testing2")
    @ApiOperation(value = "testing2", response = String.class)
    @ApiResponses({
        @ApiResponse(code = 404, message = "Not Found", response = String.class)
    })
    public String testing2() {
        return "testing2";
    }
}
```

**Generated swagger spec**
```json
{
  "swagger" : "2.0",
  "info" : { ... },
  "tags" : [ {
    "name" : "testing"
  } ],
  "schemes" : [ "https", "http" ],
  "paths" : {
    "/test/testing1" : {
      "get" : {
        "tags" : [ "testing" ],
        "summary" : "testing1",
        "description" : "",
        "operationId" : "testing1",
        "produces" : [ "application/json" ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "schema" : {
              "type" : "string"
            }
          },
          "404" : {
            "description" : "Not Found"
          }
        }
      }
    },
    "/test/testing2" : {
      "get" : {
        "tags" : [ "testing" ],
        "summary" : "testing2",
        "description" : "",
        "operationId" : "testing2",
        "produces" : [ "application/json" ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "schema" : {
              "type" : "string"
            }
          },
          "404" : {
            "description" : "Not Found"
          }
        }
      }
    }
  }
}
```

**Comment by wsalembi** [comment]
Now I see that it is only related to methods returning ```javax.ws.rs.core.Response``` 

````
    @Path("/testing1")
    @ApiOperation("testing1")
    @ApiResponses({
        @ApiResponse(code = 200, message = "OK", response = String.class),
        @ApiResponse(code = 404, message = "Not Found", response = String.class)
    })
    public Response testing1() {
        return Response.ok("test").build();
    }
```

**Comment by pavolloffay** [comment]
Is there any workaround?
