### ISSUE TITLE
NullPointerException while generating swagger.json with UUID response class using @ApiResponse annotiation

### ISSUE THREAD

**Issue by wasyl77** [kongchen/swagger-maven-plugin#295]
I used swagger @ApiResponse class to indicate what type of errors and objects are returned for api. 
Version of swagger-maven-plugin -> 3.1.2
If I put attribute response to @ApiResponse with value UUID.class it gives NullPointerException:

`@POST

    @ApiOperation(value = "do something")
    @ApiResponses(value = {
        @ApiResponse(code = SC_CREATED, message = "something created", response = UUID.class),
        @ApiResponse(code = SC_BAD_REQUEST, message = "bad request"),
        @ApiResponse(code = SC_INTERNAL_SERVER_ERROR, message = "internal server error")
    })
    public Response createSomething(@ApiParam(value = "Create something", required = true)
        SomeObject someObject);`

The exception occured:
`[ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.2:generate (default) on project my-project: null: MojoExecutionException: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.2:generate (default) on project my-project: null
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException
	at com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo.execute(ApiDocumentMojo.java:114)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.NullPointerException
	at com.github.kongchen.swagger.docgen.reader.AbstractReader.updateApiResponse(AbstractReader.java:470)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.parseMethod(JaxrsReader.java:318)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.read(JaxrsReader.java:93)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.read(JaxrsReader.java:50)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.read(JaxrsReader.java:41)
	at com.github.kongchen.swagger.docgen.mavenplugin.MavenDocumentSource.loadDocuments(MavenDocumentSource.java:46)
	at com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo.execute(ApiDocumentMojo.java:84)
	... 21 more
[ERROR]`

**Comment by pavolloffay** [comment]
Do you know some workaround?

**Comment by wasyl77** [comment]
I did not get much into details for now I just use String.class with description that identifier is returned.

**Comment by dkirrane** [comment]
Same issue with swagger-maven-plugin:3.1.2
Reverting to swagger-maven-plugin:3.1.1 solved the problem for me
