### ISSUE TITLE
Failed to execute goal for swagger-maven-plugin parameters outputFormats and attachSwaggerArtifact

### ISSUE THREAD

**Issue by jencodingatwork** [kongchen/swagger-maven-plugin#318]
I am getting the following error when I try to run my project with the parameters outputFormats and attachSwaggerArtifact. My project works when I comment them out. I have attached my pom file for your reference.
[pom.txt](https://github.com/kongchen/swagger-maven-plugin/files/223977/pom.txt)

`[ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.0:generate (default) on project swagger-java-sample-app: Unable to parse configuration of mojo com.github.kongchen:swagger-maven-plugin:3.1.0:generate for parameter outputFormats: Cannot find 'outputFormats' in class com.github.kongchen.swagger.docgen.mavenplugin.ApiSource -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.0:generate (default) on project swagger-java-sample-app: Unable to parse configuration of mojo com.github.kongchen:swagger-maven-plugin:3.1.0:generate for parameter outputFormats: Cannot find 'outputFormats' in class com.github.kongchen.swagger.docgen.mavenplugin.ApiSource
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:220)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginConfigurationException: Unable to parse configuration of mojo com.github.kongchen:swagger-maven-plugin:3.1.0:generate for parameter outputFormats: Cannot find 'outputFormats' in class com.github.kongchen.swagger.docgen.mavenplugin.ApiSource
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:689)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:621)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:121)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: org.codehaus.plexus.component.configurator.ComponentConfigurationException: Cannot find 'outputFormats' in class com.github.kongchen.swagger.docgen.mavenplugin.ApiSource
	at org.eclipse.sisu.plexus.CompositeBeanHelper.setProperty(CompositeBeanHelper.java:252)
	at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:101)
	at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.fromConfiguration(ObjectWithFieldsConverter.java:57)
	at org.codehaus.plexus.component.configurator.converters.composite.AbstractCollectionConverter.fromChildren(AbstractCollectionConverter.java:54)
	at org.codehaus.plexus.component.configurator.converters.composite.CollectionConverter.fromConfiguration(CollectionConverter.java:68)
	at org.eclipse.sisu.plexus.CompositeBeanHelper.convertProperty(CompositeBeanHelper.java:268)
	at org.eclipse.sisu.plexus.CompositeBeanHelper.setProperty(CompositeBeanHelper.java:174)
	at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:101)
	at com.github.kongchen.swagger.docgen.mavenplugin.IncludeProjectDependenciesComponentConfigurator.configureComponent(IncludeProjectDependenciesComponentConfigurator.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.component.configurator.AbstractComponentConfigurator.configureComponent(AbstractComponentConfigurator.java:61)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:659)
	... 23 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginConfigurationException
`

**Comment by benblasberg** [comment]
outputFormats was added in 3.1.1 and attachSwaggerArtifact was added in 3.1.2. It looks like you are using version 3.1.0 so you would need to upgrade to 3.1.2 to use those parameters.

**Comment by jencodingatwork** [comment]
Thank you! That fixed it. I was working off of one of the examples and didn't realize it was so far behind in the versioning.
