### ISSUE TITLE
when outputPath is null it causes build failure than rather skip static document generation

### ISSUE THREAD

**Issue by nissimpradhan** [kongchen/swagger-maven-plugin#329]
the stacktrace is given below. 

```javascript
[INFO] Writing doc to null...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.172 s
[INFO] Finished at: 2016-05-10T17:07:44+07:00
[INFO] Final Memory: 10M/25M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.3:generate (default) on project phoenix-swagger-generator: null: MojoExecutionException: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.3:generate (default) on project phoenix-swagger-generator: null
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException
        at com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo.execute(ApiDocumentMojo.java:125)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.NullPointerException
        at java.io.FileOutputStream.<init>(FileOutputStream.java:172)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:70)
        at com.github.kongchen.swagger.docgen.AbstractDocumentSource.toDocuments(AbstractDocumentSource.java:312)
        at com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo.execute(ApiDocumentMojo.java:106)
        ... 21 more
```

com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo
line 96 
```java
				if (apiSource.getOutputPath() != null){
					File outputDirectory = new File(apiSource.getOutputPath()).getParentFile();
					if (outputDirectory != null && !outputDirectory.exists()) {
						if (!outputDirectory.mkdirs()) {
							throw new MojoExecutionException("Create directory[" +
									apiSource.getOutputPath() + "] for output failed.");
						}
					}
				}
				if (apiSource.getTemplatePath()!=null) {
					documentSource.toDocuments();
				}
```
```java
				if (apiSource.getTemplatePath()!=null) {
					documentSource.toDocuments();
				}
```

should be put in the upper if clause

**Comment by nissimpradhan** [comment]
```java
[ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.3:generate (default) on project phoenix-swagger-generator: Unable to parse configuration of mojo com.github.kongchen:swagger-maven-plugin:3.1.3:generate for parameter skipSwaggerGeneration: Cannot find 'skipSwaggerGeneration' in class com.github.kongchen.swagger.docgen.mavenplugin.ApiSource -> [Help 1]
```
also skipSwaggerGeneration doesn't seem to be working on 3.1.3 where it should be working according to this

[https://github.com/kongchen/swagger-maven-plugin/tree/3.1.3-RELEASE]
