### ISSUE TITLE
Unable to generate swagger.json

### ISSUE THREAD

**Issue by gardnermer** [kongchen/swagger-maven-plugin#462]
I have the following swagger dependencies in my project:

com.wordnik:swagger-annotations:1.3.12
com.wordnik:swagger-core_2.10:1.3.12
com.wordnik:swagger-jaxrs_2.10:1.3.12
com.wordnik:swagger-jersey2-jaxrs_2.10:1.3.12

I'm unable to get the json to generate. I'm using version 3.0.1

I get this error:
[ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.0.1:generate (default) on project rmn-security-login: You may use an old version of swagger which is not supported by swagger-maven-plugin 3.0+
[ERROR] swagger-maven-plugin 3.0+ only supports swagger spec 2.0

My POM file looks like:

```
<plugin>
                <groupId>com.github.kongchen</groupId>
                <artifactId>swagger-maven-plugin</artifactId>
                <version>3.0.1</version>
                <configuration>
                    <apiSources>
                        <apiSource>
                            <springmvc>false</springmvc>
                            <locations>com.wordnik.swagger-annotations</locations>
                            <schemes>http,https</schemes>
                            <host>localhost:8080</host>
                            <basePath>/services</basePath>
                            <info> <!-- snip --> </info>
                            <swaggerDirectory>${basedir}/generated/swagger-ui</swaggerDirectory>
                            <swaggerApiReader>com.wordnik.swagger.jaxrs.reader.DefaultJaxrsApiReader</swaggerApiReader>
                        </apiSource>
                    </apiSources>
                </configuration>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

Is your project compatible with this set up? Is there a different version of the plugin I should try?

**Comment by benblasberg** [comment]
Try updating your swagger dependencies to 1.5+

**Comment by gs-vsharma** [comment]
Did you get the resolution to this isssue, I am facing it as well inspite of upgrading to 1.5+

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.0.1:generate (default) on project i: You may use an old version of swagger which is not supported by swagger-maven-plugin 3.0+
swagger-maven-plugin 3.0+ only supports swagger spec 2.0
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: You may use an old version of swagger which is not supported by swagger-maven-plugin 3.0+
swagger-maven-plugin 3.0+ only supports swagger spec 2.0
	at com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo.execute(ApiDocumentMojo.java:52)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more

**Comment by thlaegler** [comment]
Try the newest maven-plugin (3.1.5) and the newes swagger annotation (https://mvnrepository.com/artifact/io.swagger/swagger-annotations/1.5.0)

Note: the package-name/groupId changed from 'com.wordnik' to 'io.swagger'
