### ISSUE TITLE
Provide better error messages if <location> cannot be found

### ISSUE THREAD

**Issue by packleader** [kongchen/swagger-maven-plugin#500]
If one or more of the packages specified in `<locations>` cannot be found, the plugin throws several exceptions that are difficult to read.  These exceptions do not indicate the root cause of the problem and don't give the user enough information to know what's going wrong.  It would be better if the plugin could catch these exceptions and provide a useful error (or warning) message.

For example, the following configuration
```xml
<plugin>
    <groupId>com.github.kongchen</groupId>
    <artifactId>swagger-maven-plugin</artifactId>
    <version>3.1.6-SNAPSHOT</version>
    <configuration>
        <apiSources>
            <apiSource>
                <locations>
                    <!-- This package is not on the classpath -->
                    <location>package.not.found</location>
                </locations>
                <info>
                    <title>Test</title>
                    <version>0.0.1</version>
                </info>
            </apiSource>
        </apiSources>
    </configuration>
    <executions>
        <execution>
            <phase>compile</phase>
            <goals>
                <goal>generate</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```
will produce the following output repeated several times
```
[WARNING] could not create Dir using directory from url file:/Users/packleader/example/target/classes. skipping.
java.lang.NullPointerException
	at org.reflections.vfs.Vfs$DefaultUrlTypes$3.matches(Vfs.java:233)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:97)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:90)
	at org.reflections.Reflections.scan(Reflections.java:236)
        ...
[WARNING] could not create Dir using commons_vfs2 from url file:/Users/packleader/example/target/classes. skipping.
java.lang.NoClassDefFoundError: org/apache/commons/vfs2/VFS
	at org.reflections.vfs.Vfs$DefaultUrlTypes$7.matches(Vfs.java:281)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:97)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:90)
	at org.reflections.Reflections.scan(Reflections.java:236)
        ...
Caused by: java.lang.ClassNotFoundException: org.apache.commons.vfs2.VFS
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 36 more
[WARNING] could not create Vfs.Dir from url. ignoring the exception and continuing
org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/Users/packleader/example/target/classes]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:108)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:90)
	at org.reflections.Reflections.scan(Reflections.java:236)
	at org.reflections.Reflections.scan(Reflections.java:203)
        ...
```

**Comment by packleader** [comment]
Closing this as it seems to be a problem with my configuration, not the plugin.  Sorry about that...

**Comment by rmohn** [comment]
I'm having this exact issue when upgrading from 3.1.4 to 3.1.5.  You stated it was a problem in your configuration - what specifically did you find/change to address this?
