### ISSUE TITLE
Reflections spams NullPointerExceptions

### ISSUE THREAD

**Issue by packleader** [kongchen/swagger-maven-plugin#502]
If the plugin is executed as part of a project with no source directory (eg. generating swagger doc from a jar), the Reflections library will generate a large number of NPEs.  These all get logged to the console as warnings.  The plugin will still execute correctly, but it's a confusing experience for the user.  (In my case, I got 58 NPEs is a single run.)

Introduced in 3.1.5, specifically 1feeeb9bac964563e9c9d3ae9e31fb61b17edba4

To reproduce:
1. Setup a new project with no source (i.e. no `src/main/resources` and no `target/classes`)
2. Add a dependency on a jar that contains a service (eg. a Spring Boot jar)
3. Configure the plugin with `<springmvc>` set to `false`

Example output:
```
[WARNING] could not create Dir using directory from url file:/Users/packleader/example/target/classes. skipping.
java.lang.NullPointerException
	at org.reflections.vfs.Vfs$DefaultUrlTypes$3.matches(Vfs.java:233)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:97)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:90)
	at org.reflections.Reflections.scan(Reflections.java:236)
	at org.reflections.Reflections.scan(Reflections.java:203)
	at org.reflections.Reflections.<init>(Reflections.java:128)
	at org.reflections.Reflections.<init>(Reflections.java:169)
	at org.reflections.Reflections.<init>(Reflections.java:142)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.updateTagDescriptions(JaxrsReader.java:142)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.read(JaxrsReader.java:134)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.read(JaxrsReader.java:68)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.read(JaxrsReader.java:58)
	at com.github.kongchen.swagger.docgen.mavenplugin.MavenDocumentSource.loadDocuments(MavenDocumentSource.java:45)
	...
[INFO] Using "/var/folders/pz/xnt51zhx64xdpz_djcjmqc_cvzpq8m/T/vfs_cache" as temporary files store.
[WARNING] could not create Vfs.Dir from url. ignoring the exception and continuing
org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/Users/packleader/example/target/classes]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:108)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:90)
	at org.reflections.Reflections.scan(Reflections.java:236)
	at org.reflections.Reflections.scan(Reflections.java:203)
	at org.reflections.Reflections.<init>(Reflections.java:128)
	at org.reflections.Reflections.<init>(Reflections.java:169)
	at org.reflections.Reflections.<init>(Reflections.java:142)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.updateTagDescriptions(JaxrsReader.java:142)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.read(JaxrsReader.java:134)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.read(JaxrsReader.java:68)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.read(JaxrsReader.java:58)
	at com.github.kongchen.swagger.docgen.mavenplugin.MavenDocumentSource.loadDocuments(MavenDocumentSource.java:45)
	...
[WARNING] could not create Dir using directory from url file:/Users/packleader/example/src/main/resources. skipping.
java.lang.NullPointerException
	at org.reflections.vfs.Vfs$DefaultUrlTypes$3.matches(Vfs.java:233)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:97)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:90)
	at org.reflections.Reflections.scan(Reflections.java:236)
	at org.reflections.Reflections.scan(Reflections.java:203)
	at org.reflections.Reflections.<init>(Reflections.java:128)
	at org.reflections.Reflections.<init>(Reflections.java:169)
	at org.reflections.Reflections.<init>(Reflections.java:142)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.updateTagDescriptions(JaxrsReader.java:142)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.read(JaxrsReader.java:134)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.read(JaxrsReader.java:68)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.read(JaxrsReader.java:58)
	at com.github.kongchen.swagger.docgen.mavenplugin.MavenDocumentSource.loadDocuments(MavenDocumentSource.java:45)
	...
[WARNING] could not create Vfs.Dir from url. ignoring the exception and continuing
org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/Users/packleader/example/src/main/resources]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:108)
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:90)
	at org.reflections.Reflections.scan(Reflections.java:236)
	at org.reflections.Reflections.scan(Reflections.java:203)
	at org.reflections.Reflections.<init>(Reflections.java:128)
	at org.reflections.Reflections.<init>(Reflections.java:169)
	at org.reflections.Reflections.<init>(Reflections.java:142)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.updateTagDescriptions(JaxrsReader.java:142)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.read(JaxrsReader.java:134)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.read(JaxrsReader.java:68)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.read(JaxrsReader.java:58)
	at com.github.kongchen.swagger.docgen.mavenplugin.MavenDocumentSource.loadDocuments(MavenDocumentSource.java:45)
	...
[INFO] Reflections took 4745 ms to scan 316 urls, producing 10060 keys and 47375 values 
```
Also notice that it scanned 316 URLs with 10K keys and 47K values.  That seems like an awful lot.

**Comment by packleader** [comment]
@sanderbrandenburg Can you provide any insight as to why this is happening?  Thanks for your help.

**Comment by packleader** [comment]
Closing this as it seems to be a problem with my configuration, not the plugin.  Sorry about that...

**Comment by rmohn** [comment]
I'm having this exact issue when upgrading from 3.1.4 to 3.1.5. You stated it was a problem in your configuration - what specifically did you find/change to address this?

**Comment by packleader** [comment]
I don't remember for sure, but I think the dependencies in my pom were referencing conflicting versions of commons-vfs2.  Try adding an explicit dependency and let us know if it works.  If this solves the problem, we may want to make a change in the plugin's pom.
```xml
<dependency>
  <groupId>org.apache.commons</groupId>
  <artifactId>commons-vfs2</artifactId>
  <version>2.1</version>
</dependency>
```

**Comment by rmohn** [comment]
That didn't help.  After looking into this a bit more, I think the error is coming from a bug in the reflections package.  Specifically issue# 204  (https://github.com/ronmamo/reflections/issues/204).   The stacktrace and the reported error are an exact match to this issue.

**Comment by dantran** [comment]
facing this with swagger-m-p 3.1.6

**Comment by raghavkeesara** [comment]
Hi, could any of you get any solution/work-around to this problem??

**Comment by Hauk** [comment]
If this could be looked at it I would be very greatful!

**Comment by EvgeniGordeev** [comment]
Only complains if target/classes is empty. Workaround: change maven phase to compile:
```
                   <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
```

**Comment by dantran** [comment]
@EvgeniGordeev your suggestion not working for me.  

The actual workaround is to ensure target/classes created first

**Comment by Celludriel** [comment]
I'm having the same problem and while I believe target classes probably must be crated first.  I'm running in a liberty profile server and notice this

EBUG Reflections - going to scan these urls:
wsjar:file:/D:/Liberty/psp-relay/wlp/usr/servers/wlp-psp-relay/workarea/org.eclipse.osgi/121/data/cache/com.ibm.ws.app.manager_9/.cache/psp-relay-web-1.0.0-SNAPSHOT.war!/WEB-INF/classes/
WARN  Reflections - could not create Vfs.Dir from url. ignoring the exception and continuing
org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [wsjar:file:/D:/Liberty/psp-relay/wlp/usr/servers/wlp-psp-relay/workarea/org.eclipse.osgi/121/data/cache/com.ibm.ws.app.manager_9/.cache/psp-relay-web-1.0.0-SNAPSHOT.war!/WEB-INF/classes/]

it goes all the way into the WAR of my EAR to tdo something with reflections.
