### ISSUE TITLE
Latest merge broke tests

### ISSUE THREAD

**Issue by artkoshelev** [kongchen/swagger-maven-plugin#552]
I've got this on latest commit from master:
```java
Tests run: 32, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 9.184 sec <<< FAILURE!
testGeneratedSwaggerSpecJson on testGeneratedSwaggerSpecJson(com.github.kongchen.smp.integration.SwaggerReaderTest)(com.github.kongchen.smp.integration.SwaggerReaderTest)  Time elapsed: 4.136 sec  <<< FAILURE!
org.apache.maven.plugin.MojoExecutionException: unknown type: [simple type, class java.lang.Long]
	at com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo.execute(ApiDocumentMojo.java:133)
	at com.github.kongchen.smp.integration.SwaggerReaderTest.executeAndAssertGeneratedSwaggerSpecJson(SwaggerReaderTest.java:73)
	at com.github.kongchen.smp.integration.SwaggerReaderTest.testGeneratedSwaggerSpecJson(SwaggerReaderTest.java:64)
Caused by: java.lang.IllegalArgumentException: unknown type: [simple type, class java.lang.Long]
	at org.apache.commons.lang3.reflect.TypeUtils.getRawType(TypeUtils.java:1330)
	at com.github.kongchen.swagger.docgen.jaxrs.BeanParamInjectParamExtention.extractParameters(BeanParamInjectParamExtention.java:38)
	at io.swagger.jaxrs.Reader.getParameters(Reader.java:1036)
	at io.swagger.jaxrs.Reader.parseMethod(Reader.java:975)
	at io.swagger.jaxrs.Reader.read(Reader.java:322)
	at io.swagger.jaxrs.Reader.read(Reader.java:172)
	at com.github.kongchen.swagger.docgen.reader.SwaggerReader.read(SwaggerReader.java:24)
	at com.github.kongchen.swagger.docgen.AbstractDocumentSource.loadDocuments(AbstractDocumentSource.java:118)
	at com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo.execute(ApiDocumentMojo.java:96)
	... 43 more

testGeneratedSwaggerSpecYaml on testGeneratedSwaggerSpecYaml(com.github.kongchen.smp.integration.SwaggerReaderTest)(com.github.kongchen.smp.integration.SwaggerReaderTest)  Time elapsed: 4.19 sec  <<< FAILURE!
org.apache.maven.plugin.MojoExecutionException: unknown type: [simple type, class java.lang.Long]
	at com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo.execute(ApiDocumentMojo.java:133)
	at com.github.kongchen.smp.integration.SwaggerReaderTest.assertGeneratedSwaggerSpecYaml(SwaggerReaderTest.java:87)
	at com.github.kongchen.smp.integration.SwaggerReaderTest.testGeneratedSwaggerSpecYaml(SwaggerReaderTest.java:69)
Caused by: java.lang.IllegalArgumentException: unknown type: [simple type, class java.lang.Long]
	at org.apache.commons.lang3.reflect.TypeUtils.getRawType(TypeUtils.java:1330)
	at com.github.kongchen.swagger.docgen.jaxrs.BeanParamInjectParamExtention.extractParameters(BeanParamInjectParamExtention.java:38)
	at io.swagger.jaxrs.Reader.getParameters(Reader.java:1036)
	at io.swagger.jaxrs.Reader.parseMethod(Reader.java:975)
	at io.swagger.jaxrs.Reader.read(Reader.java:322)
	at io.swagger.jaxrs.Reader.read(Reader.java:172)
	at com.github.kongchen.swagger.docgen.reader.SwaggerReader.read(SwaggerReader.java:24)
	at com.github.kongchen.swagger.docgen.AbstractDocumentSource.loadDocuments(AbstractDocumentSource.java:118)
	at com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo.execute(ApiDocumentMojo.java:96)
	... 43 more


Results :

Failed tests:   testGeneratedSwaggerSpecJson on testGeneratedSwaggerSpecJson(com.github.kongchen.smp.integration.SwaggerReaderTest)(com.github.kongchen.smp.integration.SwaggerReaderTest): unknown type: [simple type, class java.lang.Long]
  testGeneratedSwaggerSpecYaml on testGeneratedSwaggerSpecYaml(com.github.kongchen.smp.integration.SwaggerReaderTest)(com.github.kongchen.smp.integration.SwaggerReaderTest): unknown type: [simple type, class java.lang.Long]
```
Rolling back to 1 commit fixes the issue.

**Comment by artkoshelev** [comment]
fix https://github.com/kongchen/swagger-maven-plugin/pull/557

**Comment by who** [comment]
merged - thank you!
