### ISSUE TITLE
Plugin doesn't work with JDK 9

### ISSUE THREAD

**Issue by umjoshi** [kongchen/swagger-maven-plugin#554]
With JDK 9.0.1 and Maven 3.5.0, I see below error:

```
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlRootElement
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:262)
	at com.github.kongchen.swagger.docgen.reader.ModelModifier.resolve(ModelModifier.java:96)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:183)
	at com.github.kongchen.swagger.docgen.reader.ModelModifier.resolve(ModelModifier.java:90)
	at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:100)
	at io.swagger.converter.ModelConverters.readAll(ModelConverters.java:83)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.parseMethod(JaxrsReader.java:282)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.read(JaxrsReader.java:107)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.read(JaxrsReader.java:68)
	at com.github.kongchen.swagger.docgen.reader.JaxrsReader.read(JaxrsReader.java:58)
	at com.github.kongchen.swagger.docgen.mavenplugin.MavenDocumentSource.loadDocuments(MavenDocumentSource.java:45)
	at com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo.execute(ApiDocumentMojo.java:96)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlRootElement
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 34 more
```

**Comment by umjoshi** [comment]
This clears up when Maven JVM is started with "--add-modules java.xml.bind".
