### ISSUE TITLE
 Cannot find setter, adder nor field in com.github.kongchen.swagger.docgen.mavenplugin.SecurityDefinition for 'in'

### ISSUE THREAD

**Issue by mamta-2018** [kongchen/swagger-maven-plugin#593]
I am using swagger-maven-plugin to generate swagger.json
          <groupId>com.github.kongchen</groupId>
          <artifactId>swagger-maven-plugin</artifactId>
          <version>3.1.1</version>
     I want to add consumerKey in header
            <securityDefinitions>
                    <securityDefinition>
                        <type>apiKey</type>
                        <in>header</in>
                        <name>ConsumerKey</name>
                  </securityDefinition>
            </securityDefinitions>

I am getting compile time error for <in>. our APIs were built on Java6, so i can't use latest swagger-plugin for this. without <in> i don't see ConsumerKey appearing in header when i try to hit my API from swaggerUI using curl, 
"curl -X GET "https://host/api" -H "accept: application/xml" -H "undefined: apiKeyValue given""

this undefined should be 'ConsumerKey'

Caused by: org.codehaus.plexus.component.configurator.ComponentConfigurationException: Cannot find setter, adder nor field in com.github.kongchen.swagger.docgen.mavenplugin.SecurityDefinition for 'in'
        at org.codehaus.plexus.component.configurator.converters.ComponentValueSetter.<init>(ComponentValueSetter.java:88)
        at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:148)

Can you help how i can resolve this?

**Comment by mamta-2018** [comment]
`         <securityDefinitions>
                    <securityDefinition>
                        <type>apiKey</type>
                        <in>header</in>
                        <name>ConsumerKey</name>
                  </securityDefinition>
       </securityDefinitions>
``
