### ISSUE TITLE
Swagger generation fails when both old and new swagger dependency is on classpath

### ISSUE THREAD

**Issue by liquidpie** [kongchen/swagger-maven-plugin#623]
Hello,

I'm using swagger maven plugin to generate the swagger files.
But, swagger generation fails when I've both older and newer swagger dependency on the classpath.

__Swagger Maven Plugin version:__ 3.1.0

__Error returned:__

```
You may use an old version of swagger which is not supported by swagger-maven-plugin 3.0+

swagger-maven-plugin 3.0+ only supports swagger spec 2.0
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: You may use an old version of swagger which is not supported by swagger-maven-plugin 3.0+
swagger-maven-plugin 3.0+ only supports swagger spec 2.0
        at com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo.execute(ApiDocumentMojo.java:52)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
```

__Swagger dependencies on `classpath`:__

```
<groupId>com.wordnik</groupId>
<artifactId>swagger-jersey2-jaxrs_2.10</artifactId>
<version>1.3.5</version>
```

```
<groupId>io.swagger</>
<artifactId>swagger-jersey2-jaxrs</artifactId>
<version>1.5.3</version>
```

Please have a look into this.

Regards,
Vivek

**Comment by AnEmortalKid** [comment]
Why do you have both dependencies on the clas path? 

Would downgrading (like the error message suggests) fix your issue?

**Comment by liquidpie** [comment]
It's a big project where some teams are still using older version and we are using newer version.
Downgrading doesn't help us and doesn't generate swagger files.
