### ISSUE TITLE
Build failed when com.github.kongchen.swagger.docgen.spring.SpringSwaggerExtension is enabled

### ISSUE THREAD

**Issue by kkee001** [kongchen/swagger-maven-plugin#717]
When Spring Swagger is turned on in pom.xml, running mvn clean package will failed.  Here is the snippet of the pom.xml

               "${basedir}/src/main/resources/template/hello.html" -->
              <swaggerApiReader>com.github.kongchen.swagger.docgen.reader.SpringMvcApiReader</swaggerApiReader>
              <swaggerExtensions>
                <swaggerExtension>com.github.kongchen.swagger.docgen.spring.SpringSwaggerExtension</swaggerExtension>
              </swaggerExtensions>
              <modelConverters>
                <modelConverter>io.swagger.validator.BeanValidator</modelConverter>
              </modelConverters>
              <swaggerDirectory>${project.basedir}/src/main/webapp/api-spec/v1</swaggerDirectory>
              <swaggerFileName>swagger</swaggerFileName>
              <outputFormats>
                json,yaml
              </outputFormats>
              <attachSwaggerArtifact>true</attachSwaggerArtifact>

[ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.8:generate (default) on project imsrestapi-web: Cannot load Swagger extension: com.github.kongchen.swagger.docgen.spring.SpringSwaggerExtension: com.github.kongchen.swagger.docgen.spring.SpringSwaggerExtension.<init>() -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.8:generate (default) on project imsrestapi-web: Cannot load Swagger extension: com.github.kongchen.swagger.docgen.spring.SpringSwaggerExtension
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Cannot load Swagger extension: com.github.kongchen.swagger.docgen.spring.SpringSwaggerExtension
        at com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo.execute(ApiDocumentMojo.java:150)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: com.github.kongchen.swagger.docgen.GenerateException: Cannot load Swagger extension: com.github.kongchen.swagger.docgen.spring.SpringSwaggerExtension
        at com.github.kongchen.swagger.docgen.AbstractDocumentSource.resolveSwaggerExtensions(AbstractDocumentSource.java:438)
        at com.github.kongchen.swagger.docgen.AbstractDocumentSource.loadSwaggerExtensions(AbstractDocumentSource.java:162)
        at com.github.kongchen.swagger.docgen.AbstractDocumentSource.loadDocuments(AbstractDocumentSource.java:106)
        at com.github.kongchen.swagger.docgen.mavenplugin.ApiDocumentMojo.execute(ApiDocumentMojo.java:122)
        ... 22 more
Caused by: java.lang.InstantiationException: com.github.kongchen.swagger.docgen.spring.SpringSwaggerExtension
        at java.lang.Class.newInstance(Class.java:427)
        at com.github.kongchen.swagger.docgen.AbstractDocumentSource.resolveSwaggerExtensions(AbstractDocumentSource.java:436)
        ... 25 more
Caused by: java.lang.NoSuchMethodException: com.github.kongchen.swagger.docgen.spring.SpringSwaggerExtension.<init>()
        at java.lang.Class.getConstructor0(Class.java:3082)
        at java.lang.Class.newInstance(Class.java:412)
        ... 26 more

**Comment by Sloloem** [comment]
Seems to be a constructor issue.  JAX-RS extension uses the default constructor but SpringMVC's extension includes a constructor that accepts the maven logger.  I have a patch.

**Comment by kkee001** [comment]
Thanks! Do you have a commit or a pull request for this?

**Comment by Sloloem** [comment]
@kkee001 There's a link to the commit above, and I also opened a PR for this project: https://github.com/kongchen/swagger-maven-plugin/pull/719

**Comment by kkee001** [comment]
Any idea when will these pull requests make it to the next release, 3.1.9?

**Comment by Sloloem** [comment]
@kkee001 Beats me, I'm not really affiliated with the project, I was just trying to use it in my own work and noticed the error.  Not sure what the release schedule is like, you'll likely need to page the repo owner.
